### PR TITLE
fix(ws): support persisted queries for `graphql-ws`

### PR DESCRIPTION
**Pull request by enisdenjo**
Code speaks for itself. [Read more for context here.](https://github.com/graphile/postgraphile/blob/cd00054ac8e2eedba6fc2030a78eae93f474557a/src/postgraphile/http/subscriptions.ts#L382-L401)

### CODE REVIEW

**Review by benjie — CHANGES_REQUESTED** [review]
This is great! The only issue is the added `graphql` peer dependency because of the number of support issues I get which turn out to be people having two different `graphql` modules installed (or they use something like yarn PnP which is overly strict).

Anyway; this is solveable - please add an `init` hook so you can get access to the GraphQL instance that PostGraphile uses (context: https://github.com/graphile/postgraphile/blob/518d9a3762fd6c49aa9d9c35b78d652c8566200d/src/postgraphile/pluginHook.ts#L225) and then use the `parse` from that instance instead of the `import`. You can then remove the changes to `package.json` that involve `graphql`.

Thanks Denis! :raised_hands:

**Comment by enisdenjo** [comment]
Done in https://github.com/graphile/persisted-operations/pull/8/commits/f7a50da1c95a343939fa5d0c4ae556f6b3cb4f58, @benjie.

You're very welcome! 😄

**Review by benjie — APPROVED** [review]
Perfect; thanks!

**Comment by benjie** [comment]
Released in `@graphile/persisted-operations@0.1.1`

**Pull request merged**
